### ISSUE TITLE
need in NuGet package

### ISSUE THREAD

**Issue by leo-gan** [wmjordan/PowerJSON#1]
Can you, please, create a NuGet package? If I have it, I would test your serializer in the GLD.SerializerBenchmark :)
Thanks!

**Comment by wmjordan** [comment]
Thank you for your interest in PowerJSON.
For full compatibility to fastJSON, PowerJSON's assembly name, namespace, classes, class members are almost the same as fastJSON's.

I've just uploaded a package to nuget: https://www.nuget.org/packages/PowerJSON/
I am new to creating NuGet packages. Please correct me if anything goes wrong.

**Comment by leo-gan** [comment]
Thanks!
Nuget package installed without problems, thanks.
The problem is in the PowerJSON namespace. It has namespace and dll names the same as fastJSON. But in my benchmark I have to install both side-by-side. If PowerJSON  had different namespace and dll name, the issue would be resolved.

**Comment by wmjordan** [comment]
For compatibility concern, its namespace and assembly name should remain the same, so the user need not to modify their source. Currently fastJSON appears to have ceased upgrading, and PowerJSON is actually a fork of fastJSON. You may use PowerJSON instead of fastJSON at this moment. And I am watching the change of fastJSON. If there are any new changes, it will be ported to PowerJSON in no time.

**Comment by leo-gan** [comment]
The point is, if you take another name, it is another package. The only way
now to test PowerJSON is to replace fastJSON, but I want to compare
PowerJSON with fastJSON side-by-side.
So the best way to avoid confusion, is to merge PowerJSON to fastJSON, if
your intention is to improve fastJSON, or change namespace to tell
everybody, that it is your product, IMO. I don't know the license of the
fastJSON, maybe it does not permit to change the name.

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

**Comment by wmjordan** [comment]
I know that you are trying to benchmark PowerJSON and fastJSON at the same application side-by-side but the assembly name and namespace conflicts prevented this.

This fork is currently revolutionizing. Many new features are adding to the library. And some APIs will be changed during the revolution. Currently the merging might not be an option, since it is Mehdi's choice whether the two projects should be merged. And I hope people switching from fastJSON to PowerJSON live their easy lives without having to change their code. It may be better being a fork for this reason.

**Comment by wmjordan** [comment]
Can this be a workaround for your issue?
_Side by side assembly loading issue_
http://stackoverflow.com/questions/14952795/side-by-side-assembly-loading-issue

**Comment by brad-jones** [comment]
Just to add my 2 cents, PowerJSON really should be in it's own namespace.
If your concerned about people having to change their code, don't be.
A simple search and replace is probably all the is needed and then there is Visual Studio's built in refactoring tools, which basically make it a one click thing.

**Comment by wmjordan** [comment]
Hi @brad-jones , recently I was just reconsidering @leo-gan 's suggestion, changing the namespace and assembly name for PowerJSON to make it go further. I am happy to hear your idea.

**Comment by wmjordan** [comment]
OK, I am now publishing a new version on nuget with its own assembly name and namespace.
The first version is 3.0.0-alpha1 (pre-release version)
