### ISSUE TITLE
Deserializing object array

### ISSUE THREAD

**Issue by Danie-Brink** [wmjordan/PowerJSON#2]
Hi,

There is a problem deserializing an object array if it contains a mix of complex types and primitives, the primitives become null:

Complex Type:

``` c#
public class TestObject
{
    public string Name { get; set; }
    public int Number { get; set; }
}
```

Serialization/Deserialization:

``` c#
TestObject t = new TestObject() { Name = "MyName", Number = 77 };
object[] o = new object[2];
o[0] = t;
o[1] = 88;

string s = JSON.ToJSON(o);
object[] result = JSON.ToObject<object[]>(s);
```

In the deserialized object result[1] is null.

**Comment by wmjordan** [comment]
Thank you for reporting this issue.
The unit test of the original fastJSON failed to catch the issue you reported.
I've just updated some code to fix the problem. However, there are still some problems after the fix, for instance, the deserialized _result_[1] will be Int64 instead of Int32. Currently I don't have the time to completely fix this issue and the workaround has to be avoiding **object[]**, or revert the type of the array items after deserialization.
